version: "3.9"

services:
  web:
    build: .
    container_name: moatalk_web
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2

    volumes:
      - .:/usr/src/moatalk
      - static_volume:/usr/src/moatalk/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    restart: always


  nginx:
    image: nginx:latest
    container_name: moatalk_nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - static_volume:/usr/src/moatalk/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always

volumes:
  static_volume: {}
