# Generated by Django 5.1.7 on 2025-04-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
