# Generated by Django 5.1.7 on 2025-04-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_friend_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
